[package]
name = "gameboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmatch = "0.1.1"
env_logger = "0.10.0"
log = "0.4.19"
pixels = "0.13.0"
winit = "0.28.6"
